### ISSUE TITLE
Healthcheck API should give more information about failing components

### ISSUE THREAD

**Issue by PabloCastellano** [Blobscan/blobscan#152]
During a debugging session to understand why is GCS storage failing, api healthcheck is not really useful as it shows Internal Server Error.

```
blobscan@blobscan-vm:~/blobscan-staging$ curl 0:3001/api/healthcheck
{"message":"\u001b[31mInternal server error\u001b[39m","code":"INTERNAL_SERVER_ERROR"}
``` 

This endpoint should check the database connection and other APIs that Blobscan relies on.

**Comment by PJColombo** [comment]
Resolved in #176
