### ISSUE TITLE
The search for the address after checksum is invalid, while the all-lowercase address works without any issues.

### ISSUE THREAD

**Issue by 4ever9** [Blobscan/blobscan#203]
examples:
1. https://blobscan.com/address/0xa055389cbccf87797952f978f01b734d06c52dba (valid)
2. https://blobscan.com/address/0xA055389cbCCf87797952f978F01b734D06C52dBa (no items)

**Comment by skywalker2017** [comment]
I'm glad to fix this

**Comment by 0xGabi** [comment]
Oh good catch @4ever9 👍. Go for it @skywalker2017!

**Comment by 0xGabi** [comment]
Close with #212 thank you @skywalker2017
