### ISSUE TITLE
Swagger baseUrl parameter should be configurable using env var

### ISSUE THREAD

**Issue by PabloCastellano** [Blobscan/blobscan#205]
https://github.com/Blobscan/blobscan/blob/39bc0b1e391f6bdc36929c1834eb085045eb46cc/apps/rest-api-server/src/openapi.ts#L1-L13

![image](https://github.com/Blobscan/blobscan/assets/73274/de4d279d-604b-484d-8979-41a2d9b7512f)

**Comment by 0xGabi** [comment]
Close by #254
