### ISSUE TITLE
The REST enndoint /blobs is.. random

### ISSUE THREAD

**Issue by tunnckoCore** [Blobscan/blobscan#332]
a) can we at least sort it to most recent first
b) also include the block number & transaction hash

Currently, it's kinda useless. The default (25 per page) is not the most recent first, and even if you put `ps=7000` (ok for now) it's still useless cuz you can't even sort it.

Also, as a side thing: webhooks per blob? Or at least per transaction with blobs?

**Comment by PJColombo** [comment]
I'll definitely start working on this right away. I'll let you know once we've patched this, @tunnckoCore.

> Also, as a side note: webhooks for each blob? Or, at the very least, for transactions involving blobs?

Yes, that could be an interesting feature. I'll create an issue.

Please, if you have more features in mind, don't hesitate to create new issues. We are eager to improve the API's functionalities as much as possible :)

**Comment by tunnckoCore** [comment]
@PJColombo awesome, thanks !

**Comment by tunnckoCore** [comment]
@PJColombo another cool thing could be actually add serial number id, to know which blob in sequence it is.

That's would be good, cuz.. regular transactions has `transactionIndex`, right?  but if we fix this thing now, and make it show in "proper order" then what's the differentiator which is after which? I mean, when you're in `/transactions` you can say okay, this blob is after this blob on that transaction. But when you are in `/blobs` then we kinda loose sense.

**Comment by PJColombo** [comment]
@tunnckoCore, hopefully, this issue will be resolved with the above PR #343 which introduces new query params that allows you to sort, filter and select which data you want from the requested resource.

The `/blobs` endpoint will return the corresponding block number and transaction hash, and the results will be sorted in the following order: by block, by transaction, and by blob index. This way, you can iterate through them in an orderly manner.
