### ISSUE TITLE
Internal server error retrieving a specific blob

### ISSUE THREAD

**Issue by vbar** [Blobscan/blobscan#373]
Going over blobs used by [zkSync Era](https://docs.zksync.io/build/) using [Blobscan API](https://api.blobscan.com/#/blobs/blob-getByBlobId), most of them can be retrieved w/o problems, but a request to 
```
https://api.blobscan.com/blobs/0x8f90b7793272e0a59a8890197f6b1c1c14ba76fcbdfa139241a2ff4ddf504fce9c45c84fbcc3f0ce666c748159b57a39
````
fails, with
```
{"message":"\u001b[31mFailed to get blob from any of the storages\u001b[39m","code":"INTERNAL_SERVER_ERROR"}
```

The ID looks correct to me, and random IDs return a specific `NOT_FOUND` code anyway.

**Comment by vbar** [comment]
This error repeats for 7 consecutive zkSync blobs and then goes away, but on just a bit more recent blobs, e.g. 

```
https://api.blobscan.com/blobs/0xb2747f359d6bf477dca2338f57acf6988c27738a8e827c9ce66dcee5c974ab5a258c05d740f9420b377b2254d4ce1215
```

the API start returning incomplete responses, e.g. for the above (with curl)

```
curl: (18) transfer closed with 164857 bytes remaining to read
```

and that problem doesn't go away (as far as I've checked)...

**Comment by PabloCastellano** [comment]
Hi @vbar. Sorry for the late reply. We have now identified the root of this issue.

**Comment by PabloCastellano** [comment]
@vbar This should be fixed now but please reopen if the issue persists.
