### ISSUE TITLE
Job for updating Swarm batchTTL

### ISSUE THREAD

**Issue by PabloCastellano** [Blobscan/blobscan#383]
* [ ] Add fields `updatedAt`, `batchLabel` and `batchUsage` to the BlobStoragesState table
* [ ] Create a job that runs every hour and updates swarmDataTTL and batchUsage
* [ ] Allow configuring swarm batch id using environment variable (if the batch id is not present in the database, add it)

**Comment by PJColombo** [comment]
Resolved on PR #411
