### ISSUE TITLE
feat: Add Scroll contracts for mainnet and Sepolia

### ISSUE THREAD

**Issue by dghelm** [Blobscan/blobscan#391]
With Scroll now using blobs, it'd be great to add support in the UI for Scroll:

mainnet: [`0xa13baf47339d63b743e7da8741db5456dac1e556`](https://etherscan.io/address/0xa13baf47339d63b743e7da8741db5456dac1e556)

sepolia: [`0x2D567EcE699Eabe5afCd141eDB7A4f2D0D6ce8a0`](https://sepolia.etherscan.io/address/0x2D567EcE699Eabe5afCd141eDB7A4f2D0D6ce8a0)

Icons available in [Brand Kit](https://scroll.io/brand-kit)

**Comment by 0xGabi** [comment]
Hi @dghelm  thank you for the suggestion. We already include the changes for mainnet https://github.com/Blobscan/blobscan/pull/387 (will include Sepolia as well). We are waiting to resolve a couple of issues before include the changes into production.

**Comment by dghelm** [comment]
Oh, amazing! 🙏🙏
