### ISSUE TITLE
feat: Add Kroma Network for mainnet and sepolia

### ISSUE THREAD

**Issue by sm-stack** [Blobscan/blobscan#392]
[Kroma Network](https://kroma.network/) has started to support blobs from 4/25, and it would be great to see supports for its icons on blobscan.

Kroma is based on OP-stack, and has the same architecture as Optimism when submitting batches. Our batcher / batch inbox addresses for mainnet & sepolia is as follows:

Mainnet batcher address: [`0x41b8cd6791de4d8f9e0eaf7861ac506822adce12`](https://etherscan.io/address/0x41b8cd6791de4d8f9e0eaf7861ac506822adce12)
Mainnet Batch Inbox address: [`0xFF00000000000000000000000000000000000255`](https://etherscan.io/address/0xFF00000000000000000000000000000000000255)
Sepolia batcher address: [`0xf15dc770221b99c98d4aaed568f2ab04b9d16e42`](https://sepolia.etherscan.io/address/0xf15dc770221b99c98d4aaed568f2ab04b9d16e42)
Sepolia Batch Inbox address: [`0xfA79000000000000000000000000000000000001`](https://sepolia.etherscan.io/address/0xfa79000000000000000000000000000000000001)

You can find the icons by downloading our [brand kit](https://cdn.kroma.network/hub/etc/Kroma%20BI.zip).

**Comment by 0xGabi** [comment]
Hi @sm-stack thank you for the suggestion. We already include the changes for mainnet #387 (will include Sepolia as well). We are waiting to resolve a couple of issues before include the changes into production.

**Comment by sm-stack** [comment]
Oh I missed it, thanks:)
