### ISSUE TITLE
Project Fit Discussion

### ISSUE THREAD

**Issue by Ben2012334** [Blobscan/blobscan#611]
Hi Julien,
Reaching out here as I thought you might be interested in a challenging project involving SMPC, zk proofs, and scaling solutions. Your work stands out and looks like a strong match. 
If you’re open to a chat, feel free to reach me directly at benedykt@talentnetwork.io. Thanks!

**Comment by PabloCastellano** [comment]
@Ben2012334 This is not an issue with Blobscan. Please do not use this channel to promote your services.
