### ISSUE TITLE
Error 500 in blob.getByIndex 

### ISSUE THREAD

**Issue by PabloCastellano** [Blobscan/blobscan#93]
See https://staging.blobscan.com/tx/0x160b7ba1290e85fc788d8309007a7ddec22477ff8d00aab070db3286c0b24f02/blob/0 or https://blobscan.com/tx/0x97f731111247c8377283b30fa675a61232f396b45166e925a7dff65f0d181cd9/blob/0

Request:

`GET | https://staging.blobscan.com/api/trpc/blob.getByIndex?input={"json":{"index":0,"txHash":"0x160b7ba1290e85fc788d8309007a7ddec22477ff8d00aab070db3286c0b24f02"}}`

Response:

```
{
	"error": {
		"json": {
			"message": "Internal server error",
			"code": -32603,
			"data": {
				"code": "INTERNAL_SERVER_ERROR",
				"httpStatus": 500,
				"path": "blob.getByIndex"
			}
		}
	}
}
```

Related: https://github.com/Blobscan/blobscan/issues/90

**Comment by 0xGabi** [comment]
I think this is no longer an issue anymore. Let's open again if it reminds.
